### ISSUE TITLE
docker run configuration?

### ISSUE THREAD

**Issue by la0wei** [bernarden/docker-debian-kimchi-build#1]
hello,any other configuration need when run docker run after build image?

**Comment by bernarden** [comment]
Hi. I would like to note that I used this image when I was trying to install Kimchi on Debian without having to build it on the actual machine. Since then I gave up on that, built and installed on the server from the source code. So this image might not be of any use for you, since it doesn't even solve the issue with libvirt dependency on Debian during the installation of the generated .deb package.

**Comment by la0wei** [comment]
Thank you all the same.
